### ISSUE TITLE
size mismatch for head.weight

### ISSUE THREAD

**Issue by yangjingqi99** [Lucienxhh/FS2K_MAE_Classification#1]
楼主您好，请问改了分类类别数后您运行这个 misc.load_model(args=args, model_without_ddp=model_without_ddp, optimizer=optimizer, loss_scaler=loss_scaler)函数会报错吗？
![image](https://user-images.githubusercontent.com/57439185/188594414-eaa29551-2f0c-4eb0-a2ad-87c796a68ea6.png)

**Comment by Lucienxhh** [comment]
你一开始不修改能运行吗？我没遇到过你这个问题。

**Comment by yangjingqi99** [comment]
> 

感谢您的回复，现在可以运行了。我调试main_finetune时发现dataset_train和dataset_val都是验证集：
![image](https://user-images.githubusercontent.com/57439185/189268143-7b8c3d23-ba7a-424f-a4b3-7920e59938bb.png)

请问您dataset这里是不是误加了一行代码：
![image](https://user-images.githubusercontent.com/57439185/189268425-6f741352-555a-45be-812a-105e83604dbc.png)

**Comment by Lucienxhh** [comment]
感谢你的指正。我已修正了代码逻辑，具体参见datasets.py。
